Entity/UnicatAttribute.php
<?php

namespace SmartCore\Module\Unicat\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Smart\CoreBundle\Doctrine\ColumnTrait;
use SmartCore\Bundle\CMSBundle\Container;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Yaml\Yaml;

/**
 * @ORM\Entity(repositoryClass="SmartCore\Module\Unicat\Entity\UnicatAttributeRepository")
 * @ORM\Table(name="unicat__attributes",
 *      indexes={
 *          @ORM\Index(columns={"is_enabled"}),
 *          @ORM\Index(columns={"show_in_admin"}),
 *          @ORM\Index(columns={"show_in_list"}),
 *          @ORM\Index(columns={"show_in_view"}),
 *          @ORM\Index(columns={"position"}),
 *      },
 *      uniqueConstraints={
 *          @ORM\UniqueConstraint(columns={"name", "configuration_id"}),
 *      },
 * )
 *
 * @UniqueEntity(fields={"name", "configuration"}, message="Имя атрибута должно быть уникальным.")
 */
class UnicatAttribute
{
    use ColumnTrait\Id;
    use ColumnTrait\IsEnabled;
    use ColumnTrait\CreatedAt;
    use ColumnTrait\Description;
    use ColumnTrait\Position;
    use ColumnTrait\TitleNotBlank;
    use ColumnTrait\FosUser;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     * @Assert\NotBlank()
     * @Assert\Regex(
     *      pattern="/^[a-z][a-z0-9_]+$/",
     *      htmlPattern="^[a-z][a-z0-9_]+$",
     *      message="Имя может состоять только из латинских букв в нижнем регистре, символов подчеркивания и цифр, но первый символ должен быть буква."
     * )
     *
     * @todo перевод сообщения
     */
    protected $name;

    /**
     * @ORM\Column(type="string", length=32)
     */
    protected $type;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true, options={"default":"<p>"})
     */
    protected $open_tag;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true, options={"default":"</p>"})
     */
    protected $close_tag;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default":0})
     */
    protected $is_dedicated_table;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default":0})
     */
    protected $is_link;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default":0})
     */
    protected $is_required;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default":1})
     */
    protected $is_show_title;

    /**
     * Отсновной атрибут? Используется для фильтрации "основные" и "все" свойства.
     *
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default":1})
     */
    protected $is_primary;

    /**
     * Отображать в списке администратора.
     *
     * @var bool
     *
     * @ORM\Column(type="boolean")
     */
    protected $show_in_admin;

    /**
     * Отображать в списке записей.
     *
     * @var bool
     *
     * @ORM\Column(type="boolean")
     */
    protected $show_in_list;

    /**
     * Отображать при просмотре записи.
     *
     * @var bool
     *
     * @ORM\Column(type="boolean")
     */
    protected $show_in_view;

    /**
     * @var array
     *
     * @ORM\Column(type="array")
     */
    protected $params;

    /**
     * @var array
     *
     * @ORM\Column(type="text", nullable=true)
     */
    protected $params_yaml;

    /**
     * Связывать items_type (если указан) как "много ко многим".
     *
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default":0})
     */
    protected $is_items_type_many2many;

    /**
     * @var UnicatConfiguration
     *
     * @ORM\ManyToOne(targetEntity="UnicatConfiguration", inversedBy="attributes")
     */
    protected $configuration;

    /**
     * Атрибут - колекция других типов записей.
     *
     * @var UnicatItemType|null
     *
     * @ORM\ManyToOne(targetEntity="UnicatItemType")
     */
    protected $items_type;

    /**
     * @var UnicatAttributesGroup[]|ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="UnicatAttributesGroup", inversedBy="attributes", cascade={"persist"}, fetch="EXTRA_LAZY")
     * @ORM\JoinTable(name="unicat__attributes_groups_relations",
     *      joinColumns={@ORM\JoinColumn(name="attribute_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="group_id", referencedColumnName="id")}
     * )
     */
    protected $groups;

    /**
     * @var string
     */
    protected $update_all_records_with_default_value;

    /**
     * UnicatAttribute constructor.
     */
    public function __construct()
    {
        $this->created_at       = new \DateTime();
        $this->groups           = new ArrayCollection();
        $this->is_dedicated_table = false;
        $this->is_enabled       = true;
        $this->is_link          = false;
        $this->is_required      = false;
        $this->is_show_title    = true;
        $this->is_primary       = true;
        $this->is_items_type_many2many = false;
        $this->show_in_view     = true;
        $this->params           = [];
        $this->params_yaml      = null;
        $this->position         = 0;
        $this->open_tag         = '<p>';
        $this->close_tag        = '</p>';
    }

    /**
     * @see getName
     *
     * @return string
     */
    public function __toString()
    {
        return (string) $this->getName();
    }

    /**
     * @return null|string
     */
    public function getValueClassName()
    {
        if ($this->is_dedicated_table) {
            $className = 'Value';

            foreach (explode('_', $this->name) as $namePart) {
                $className .= ucfirst($namePart);
            }

            return $className;
        }

        return null;
    }

    /**
     * Получить значение из списка.
     *
     * @param int|string $id
     *
     * @return int|null|string
     */
    public function getValueByChoice($id)
    {
        if (isset($this->params['form']['choices'])) {
            foreach ($this->params['form']['choices'] as $name => $value) {
                if ($value == $id) {
                    return $name;
                }
            }
        }

        return null;
    }

    /**
     * Получение имени в формате CamelCase
     *
     * @return string
     */
    public function getNameCamelCase()
    {
        $str = '';
        foreach (explode('_', $this->getName()) as $val) {
            if (!empty($val)) {
                $str .= ucfirst($val);
            }
        }

        return $str;
    }

    /**
     * Получение вариантов выбора для типа choice
     *
     * @return array|bool
     */
    public function getChoices()
    {
        $choices = [];
        if (isset($this->params['form']['choices'])) {
            $choices = array_flip($this->params['form']['choices']);
        }

        return $choices;
    }

    /**
     * @return string
     */
    public function getValueClassNameWithNameSpace()
    {
        return $this->getConfiguration()->getEntitiesNamespace().$this->getValueClassName();
    }

    /**
     * @param bool $is_dedicated_table
     *
     * @return $this
     */
    public function setIsDedicatedTable($is_dedicated_table)
    {
        $this->is_dedicated_table = $is_dedicated_table;

        return $this;
    }

    /**
     * @return bool
     */
    public function isDedicatedTable()
    {
        return $this->is_dedicated_table;
    }

    /**
     * @return bool
     */
    public function getIsDedicatedTable()
    {
        return $this->is_dedicated_table;
    }

    /**
     * @return bool
     */
    public function isIsLink()
    {
        return $this->is_link;
    }

    /**
     * @param bool $is_link
     *
     * @return $this
     */
    public function setIsLink($is_link)
    {
        $this->is_link = $is_link;

        return $this;
    }

    /**
     * @param bool $is_required
     *
     * @return $this
     */
    public function setIsRequired($is_required)
    {
        $this->is_required = $is_required;

        return $this;
    }

    /**
     * @return bool
     */
    public function getIsRequired()
    {
        return $this->is_required;
    }

    /**
     * @return bool
     */
    public function isIsShowTitle()
    {
        return $this->is_show_title;
    }

    /**
     * @param bool $is_show_title
     *
     * @return $this
     */
    public function setIsShowTitle($is_show_title)
    {
        $this->is_show_title = $is_show_title;

        return $this;
    }

    /**
     * @return bool
     */
    public function isIsPrimary(): bool
    {
        return $this->is_primary;
    }

    /**
     * @param bool $is_primary
     *
     * @return $this
     */
    public function setIsPrimary($is_primary)
    {
        $this->is_primary = $is_primary;

        return $this;
    }

    /**
     * @return bool
     */
    public function getIsItemsTypeMany2many(): bool
    {
        return $this->is_items_type_many2many;
    }

    /**
     * @return bool
     */
    public function isItemsTypeMany2many(): bool
    {
        return $this->is_items_type_many2many;
    }

    /**
     * @param bool $is_items_type_many2many
     *
     * @return $this
     */
    public function setIsItemsTypeMany2many($is_items_type_many2many)
    {
        $this->is_items_type_many2many = $is_items_type_many2many;

        return $this;
    }

    /**
     * @return UnicatAttributesGroup[]|ArrayCollection
     */
    public function getGroups()
    {
        return $this->groups;
    }

    /**
     * @param UnicatAttributesGroup[] $groups
     *
     * @return $this
     */
    public function setGroups($groups)
    {
        $this->groups = $groups;

        return $this;
    }

    /**
     * @param array $params
     *
     * @return $this
     */
    public function setParams(array $params = [])
    {
        $this->params = $params;

Entity/UnicatConfiguration.php
<?php

namespace SmartCore\Module\Unicat\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Smart\CoreBundle\Doctrine\ColumnTrait;
use SmartCore\Bundle\MediaBundle\Entity\Collection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity()
 * @ORM\Table(name="unicat__configurations",
 *      uniqueConstraints={
 *          @ORM\UniqueConstraint(columns={"title"}),
 *      }
 * )
 * @UniqueEntity(fields={"name"}, message="Конфигурация с таким именем уже существует.")
 * @UniqueEntity(fields={"title"}, message="Конфигурация с таким заголовком уже существует.")
 */
class UnicatConfiguration
{
    use ColumnTrait\Id;
    use ColumnTrait\CreatedAt;
    use ColumnTrait\NameUnique;
    use ColumnTrait\TitleNotBlank;
    use ColumnTrait\FosUser;

    /**
     * Пространство имен сущностей, например: DemoSiteBundle\Entity\Catalog\.
     *
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     */
    protected $entities_namespace;

    /**
     * Включает записи вложенных категорий.
     *
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default":1})
     */
    protected $is_inheritance;

    /**
     * @var int
     *
     * @ORM\Column(type="smallint", options={"default":10, "unsigned"=true})
     */
    protected $items_per_page;

    /**
     * @var Collection
     *
     * @ORM\ManyToOne(targetEntity="SmartCore\Bundle\MediaBundle\Entity\Collection")
     */
    protected $media_collection;

    /**
     * @var UnicatTaxonomy|null
     *
     * @ORM\ManyToOne(targetEntity="UnicatTaxonomy")
     */
    protected $default_taxonomy;

    /**
     * @var UnicatAttribute[]
     *
     * @ORM\OneToMany(targetEntity="UnicatAttribute", mappedBy="configuration")
     * @ORM\OrderBy({"position" = "ASC"})
     */
    protected $attributes;

    /**
     * @var UnicatAttributesGroup[]
     *
     * @ORM\OneToMany(targetEntity="UnicatAttributesGroup", mappedBy="configuration")
     */
    protected $attributes_groups;

    /**
     * @var UnicatItemType[]
     *
     * @ORM\OneToMany(targetEntity="UnicatItemType", mappedBy="configuration")
     * @ORM\OrderBy({"position" = "ASC"})
     */
    protected $item_types;

    /**
     * @var UnicatTaxonomy[]
     *
     * @ORM\OneToMany(targetEntity="UnicatTaxonomy", mappedBy="configuration")
     */
    protected $taxonomies;

    /**
     * UnicatConfiguration constructor.
     */
    public function __construct()
    {
        $this->created_at           = new \DateTime();
        $this->is_inheritance       = true;
        $this->items_per_page       = 10;
        $this->entities_namespace   = null;
        $this->item_types           = new ArrayCollection();
        $this->taxonomies           = new ArrayCollection();
    }

    /**
     * @return string
     */
    public function __toString()
    {
        return $this->title;
    }

    /**
     * @return string
     */
    public function getTaxonClass()
    {
        return $this->entities_namespace.'Taxon';
    }

    /**
     * @return string
     */
    public function getItemClass()
    {
        return $this->entities_namespace.'Item';
    }

    /**
     * @param string $entities_namespace
     *
     * @return $this
     */
    public function setEntitiesNamespace($entities_namespace)
    {
        $this->entities_namespace = $entities_namespace;

        return $this;
    }

    /**
     * @return string
     */
    public function getEntitiesNamespace()
    {
        return $this->entities_namespace;
    }

    /**
     * @param bool $is_inheritance
     *
     * @return $this
     */
    public function setIsInheritance($is_inheritance)
    {
        $this->is_inheritance = $is_inheritance;

        return $this;
    }

    /**
     * @return bool
     */
    public function getIsInheritance()
    {
        return $this->is_inheritance;
    }

    /**
     * @return bool
     */
    public function isInheritance()
    {
        return $this->is_inheritance;
    }

    /**
     * @param Collection|null $media_collection
     *
     * @return $this
     */
    public function setMediaCollection(Collection $media_collection = null)
    {
        $this->media_collection = $media_collection;

        return $this;
    }

    /**
     * @return Collection|null
     */
    public function getMediaCollection()
    {
        return $this->media_collection;
    }

    /**
     * @return UnicatAttribute[]
     */
    public function getAttributes()
    {
        return $this->attributes;
    }

    /**
     * @param UnicatAttribute[] $attributes
     *
     * @return $this
     */
    public function setAttributes($attributes)
    {
        $this->attributes = $attributes;

        return $this;
    }

    /**
     * @return UnicatItemType[]|ArrayCollection
     */
    public function getItemTypes()
    {
        return $this->item_types;
    }

    /**
     * @param UnicatItemType[] $item_types
     *
     * @return $this
     */
    public function setItemTypes($item_types)
    {
        $this->item_types = $item_types;

        return $this;
    }

    /**
     * @return UnicatAttributesGroup[]
     */
    public function getAttributesGroups()
    {
        return $this->attributes_groups;
    }

    /**
     * @param UnicatAttributesGroup[] $attributes_groups
     *
     * @return $this
     */
    public function setAttributesGroups($attributes_groups)
    {
        $this->attributes_groups = $attributes_groups;

        return $this;
    }

    /**
     * @return UnicatTaxonomy[]
     */
    public function getTaxonomies()
    {
        return $this->taxonomies;
    }

    /**
     * @param UnicatTaxonomy[]|ArrayCollection $taxonomies
     *
     * @return $this
     */
    public function setTaxonomies($taxonomies)
    {
        $this->taxonomies = $taxonomies;

        return $this;
    }

    /**
     * @return UnicatTaxonomy
     */
    public function getDefaultTaxonomy()
    {
        return $this->default_taxonomy;
    }

    /**
     * @param UnicatTaxonomy $default_taxonomy
     *
     * @return $this
     */
    public function setDefaultTaxonomy(UnicatTaxonomy $default_taxonomy = null)
    {
        $this->default_taxonomy = $default_taxonomy;

        return $this;
    }

    /**
     * @return int
     */
    public function getItemsPerPage()
    {
        return $this->items_per_page;
    }

    /**
     * @param int $items_per_page
     *
     * @return $this
     */
    public function setItemsPerPage($items_per_page)
    {
        if ($items_per_page < 1) {
            $items_per_page = 10;
        }

        $this->items_per_page = $items_per_page;

        return $this;
    }
}

Resources/views/category_tree.html.twig
{% if not depth %}
    {% set depth = null %}
{% endif %}

{% if not template %}
    {% set template = 'knp_menu.html.twig' %}
{% endif %}

{% set menuItem = knp_menu_get('UnicatModule:CategoryMenu:tree', [], {
    'categoryClass': categoryClass,
    'css_class': css_class,
    'depth': depth,
    'routeName': routeName,
    'structure': structure,
}) %}

{{ knp_menu_render(menuItem, {
    'currentClass': 'active',
    'clear_matcher': false,
    'template': template,
}) }}

Resources/views/index.html.twig
{% if childenTaxons|length %}
    <h4>Вложенные категории:</h4>

    <ul>
        {% for taxon in childenTaxons %}
            <li><a href="{{ path('unicat.index', {'slug': taxon.slugFull}) }}/">{{ taxon }}</a></li>
        {% endfor %}
    </ul>
    <hr />
{% endif %}

<p>Всего записей: <b>{{ pagerfanta.count }}</b>
    {% if pagerfanta.haveToPaginate %} Страница: {{ pagerfanta.currentPage }} Записей на страницу: {{ pagerfanta.maxPerPage }}{% endif %}
</p>

{% for item in pagerfanta %}

    {% include '@UnicatModule/item.html.twig' %}

{% endfor %}

{% if pagerfanta.haveToPaginate %}
    Страница: {{ pagerfanta.currentPage }} Записей на страницу: {{ pagerfanta.maxPerPage }}

    {% if slug %}
        {% set pagerfantaRouteName = 'unicat.index' %}
    {% else %}
        {% set pagerfantaRouteName = 'unicat.root' %}
    {% endif %}

    {{ pagerfanta(pagerfanta, 'twitter_bootstrap_translated', {
        'routeName': pagerfantaRouteName,
        'routeParams': {'slug': slug},
        'css_container_class': 'pagination pagination-centered',
    })
    }}
{% endif %}

Resources/views/item.html.twig
{% set item_link = null %}

{% for attr in attributes %}
    {% if attr.isShowIn(mode) and item.hasAttribute(attr.name) %}
        {# @todo сделать линки более универсальные #}
        {% if attr.isLink and mode == 'list' %}
            {% set is_found_default_taxonomy = false %}
            {% for taxon in item.taxons %}
                {% if configuration.defaultTaxonomy.id == taxon.taxonomy.id and is_found_default_taxonomy == false %}
                    {{ attr.openTag }}
                        <a href="{{ path('unicat.item_in_taxonomy', {'taxonomySlug': taxon.slugFull, 'itemSlug': item.slug}) }}">{{ item.attribute(attr.name) }}</a>
                    {{ attr.closeTag }}
                    {% set is_found_default_taxonomy = true %}
                {% endif %}
            {% endfor %}
            {% if is_found_default_taxonomy == false %}
                {% if attr.type == 'image' %}
                    {{ attr.openTag }}<a href="{{ path('unicat.item', {'itemSlug': item.slug}) }}">{{ smart_media_img(item.attribute(attr.name), attr.params.filter) }}</a>{{ attr.closeTag }}
                {% else %}
                    {{ attr.openTag }}<a href="{{ path('unicat.item', {'itemSlug': item.slug}) }}">{{ item.attribute(attr.name) }}</a>{{ attr.closeTag }}
                {% endif %}
            {% endif %}
        {% elseif attr.type == 'checkbox' %}
            {{ attr.openTag }}{{ attr.title }}: {% if item.attribute(attr.name) %} да {% else %} нет {% endif %}{{ attr.closeTag }}
        {% elseif attr.type == 'image' %}
            {{ attr.openTag }}{{ smart_media_img(item.attribute(attr.name), attr.params.filter) }}{{ attr.closeTag }}
        {% elseif attr.type == 'date' or attr.type == 'datetime' %}
            {% if val is not empty %}
                {{ attr.openTag }}
                {{ item.attribute(attr.name)|localizeddate }}
                {{ attr.closeTag }}
            {% endif %}
        {% elseif attr.type == 'gallery' %}
            {{ attr.openTag }}
            {% if attr.isShowTitle %}{{ attr.title }}: {% endif %}

            {% for img in item.attribute(attr.name) %}
                {{ smart_media_img(img.id, attr.params.filter) }}
            {% endfor %}
            {{ attr.closeTag }}
        {% else %}
            {{ attr.openTag }}
            {% if attr.isShowTitle %}{{ attr.title }}: {% endif %}
            {% set val = item.attribute(attr.name) %}
            {% if val is iterable %}
                <ul>
                    {% for v in val  %}
                        <li>{{ v }}</li>
                    {% endfor %}
                </ul>
            {% else %}
                {{ val }}
            {% endif %}
            {{ attr.closeTag }}
        {% endif %}
    {% endif %}
{% endfor %}

<hr />

Resources/views/items.html.twig
{% if childenTaxons|length %}
    <h4>Вложенные категории:</h4>

    <ul>
        {% for taxon in childenTaxons %}
            <li><a href="{{ path('unicat.taxon', {'slug': taxon.slugFull}) }}/">{{ taxon }}</a></li>
        {% endfor %}
    </ul>
    <hr />
{% endif %}

<p>Всего записей: <b>{{ pagerfanta.count }}</b>
    {% if pagerfanta.haveToPaginate %} Страница: {{ pagerfanta.currentPage }} Записей на страницу: {{ pagerfanta.maxPerPage }}{% endif %}
</p>

{% for item in pagerfanta %}

    {% include 'UnicatModule::item.html.twig' %}

{% endfor %}

{% if pagerfanta.haveToPaginate %}
    Страница: {{ pagerfanta.currentPage }} Записей на страницу: {{ pagerfanta.maxPerPage }}

    {% if slug %}
        {% set pagerfantaRouteName = 'unicat.taxon' %}
    {% else %}
        {% set pagerfantaRouteName = 'unicat.taxon_root' %}
    {% endif %}

    {{ pagerfanta(pagerfanta, 'twitter_bootstrap_translated', {
        'routeName': pagerfantaRouteName,
        'routeParams': {'slug': slug},
        'css_container_class': 'pagination pagination-centered',
    })
    }}
{% endif %}

Resources/views/node_properties_form.html.twig
{% form_theme form_properties '@CMS/Form/bootstrap_wide.html.twig' %}
{{ form_widget(form_properties) }}

<style type="text/css" media="screen">
    .ace_editor * {
        font-family: consolas, Courier, monospace;
        font-size: 14px;
    }

    #ace_params_yaml,
    #smart_module_unicat_node_properties_params
    {
        font-family: consolas, Courier, monospace;
        font-size: 14px;
        width: 100%;
        height: 200px;
    }
</style>

<script src="{{ asset('bundles/felib/ace/ace.js') }}" type="text/javascript" charset="utf-8"></script>
<script>
    $('#smart_module_unicat_node_properties_params_control_group > .controls').append('<div id="ace_params_yaml" />');
    var editor = ace.edit("ace_params_yaml");
    var textarea = $('#smart_module_unicat_node_properties_params').hide();
    editor.setTheme("ace/theme/github");
    editor.getSession().setMode("ace/mode/yaml");
    editor.getSession().setValue(textarea.val());
    editor.getSession().on('change', function(){
        textarea.val(editor.getSession().getValue());
    });
</script>

Resources/views/taxon_tree.html.twig
{% if not depth %}
    {% set depth = null %}
{% endif %}

{% if not template %}
    {% set template = 'knp_menu.html.twig' %}
{% endif %}

{% set menuItem = knp_menu_get('UnicatModuleBundle:TaxonMenu:tree', [], {
    'taxonClass': taxonClass,
    'css_class':  css_class,
    'depth':      depth,
    'routeName':  routeName,
    'taxonomy':  taxonomy,
}) %}

{{ knp_menu_render(menuItem, {
    'currentClass': 'active',
    'clear_matcher': false,
    'template': template,
}) }}