Entity/UnicatAttributesGroup.php
<?php

namespace SmartCore\Module\Unicat\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Smart\CoreBundle\Doctrine\ColumnTrait;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity()
 * @ORM\Table(name="unicat__attributes_groups",
 *      indexes={
 *          @ORM\Index(columns={"position"}),
 *      },
 *      uniqueConstraints={
 *          @ORM\UniqueConstraint(columns={"name", "configuration_id"}),
 *      },
 * )
 *
 * @UniqueEntity(fields={"name", "configuration"}, message="Имя должно быть уникальным.")
 */
class UnicatAttributesGroup
{
    use ColumnTrait\Id;
    use ColumnTrait\CreatedAt;
    use ColumnTrait\Name;
    use ColumnTrait\Position;
    use ColumnTrait\TitleNotBlank;

    /**
     * @var UnicatAttribute[]
     *
     * @ORM\ManyToMany(targetEntity="UnicatAttribute", mappedBy="groups")
     */
    protected $attributes;

    /**
     * @var UnicatItemType[]
     *
     * @ORM\ManyToMany(targetEntity="UnicatItemType", mappedBy="attributes_groups")
     */
    protected $item_types;

    /**
     * @todo подумать о привязке групп атрибутов к таксону
     *
     * @var TaxonModel
     *
     * ORM\ManyToOne(targetEntity="Taxon")
     **/
    //protected $taxon;

    /**
     * @var UnicatConfiguration
     *
     * @ORM\ManyToOne(targetEntity="UnicatConfiguration", inversedBy="attributes_groups")
     **/
    protected $configuration;

    /**
     * UnicatAttributesGroup constructor.
     */
    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->attributes = new ArrayCollection();
        $this->position   = 0;
    }

    /**
     * @see getName
     *
     * @return string
     */
    public function __toString()
    {
        return (string) $this->getTitle();
    }

    /**
     * @param UnicatAttribute[] $attributes
     *
     * @return $this
     */
    public function setAttributes($attributes)
    {
        $this->attributes = $attributes;

        return $this;
    }

    /**
     * @return UnicatAttribute[]
     */
    public function getAttributes()
    {
        return $this->attributes;
    }

    /**
     * @param UnicatConfiguration $configuration
     *
     * @return $this
     */
    public function setConfiguration(UnicatConfiguration $configuration)
    {
        $this->configuration = $configuration;

        return $this;
    }

    /**
     * @return UnicatConfiguration
     */
    public function getConfiguration()
    {
        return $this->configuration;
    }

    /**
     * @return UnicatItemType[]
     */
    public function getItemTypes()
    {
        return $this->item_types;
    }

    /**
     * @param mixed $item_types
     *
     * @return $this
     */
    public function setItemTypes($item_types)
    {
        $this->item_types = $item_types;

        return $this;
    }
}

Entity/UnicatItemType.php
<?php

namespace SmartCore\Module\Unicat\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Smart\CoreBundle\Doctrine\ColumnTrait;

/**
 * @ORM\Entity()
 * @ORM\Table(name="unicat__items_types",
 *      indexes={
 *          @ORM\Index(columns={"name"}),
 *      }
 * )
 */
class UnicatItemType
{
    use ColumnTrait\Id;
    use ColumnTrait\CreatedAt;
    use ColumnTrait\Name;
    use ColumnTrait\Position;
    use ColumnTrait\TitleNotBlank;
    use ColumnTrait\FosUser;

    /**
     * @var integer|null
     *
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $content_min_width;

    /**
     * @var string|null
     *
     * @ORM\Column(type="string", nullable=true)
     */
    protected $order_by_attr;

    /**
     * @var string|null
     *
     * @ORM\Column(type="string", nullable=true)
     */
    protected $order_by_direction;

    /**
     * @var string|null
     *
     * @ORM\Column(type="string", nullable=true)
     */
    protected $to_string_pattern;

    /**
     * @var UnicatConfiguration
     *
     * @ORM\ManyToOne(targetEntity="UnicatConfiguration", inversedBy="item_types")
     */
    protected $configuration;

    /**
     * @var UnicatAttributesGroup[]|ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="UnicatAttributesGroup", inversedBy="item_types", cascade={"persist"}, fetch="EXTRA_LAZY")
     * @ORM\JoinTable(name="unicat__items_types_attributes_groups_relations",
     *      joinColumns={@ORM\JoinColumn(name="attribute_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="group_id", referencedColumnName="id")}
     * )
     */
    protected $attributes_groups;

    /**
     * @var UnicatTaxonomy[]|ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="UnicatTaxonomy", inversedBy="item_types", cascade={"persist"}, fetch="EXTRA_LAZY")
     * @ORM\JoinTable(name="unicat__items_types_taxonomies_relations",
     *      joinColumns={@ORM\JoinColumn(name="attribute_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="taxonomy_id", referencedColumnName="id")}
     * )
     * @ORM\OrderBy({"position" = "ASC", "id" = "ASC"})
     */
    protected $taxonomies;

    /**
     * UnicatItemType constructor.
     */
    public function __construct()
    {
        $this->attributes_groups = new ArrayCollection();
        $this->content_min_width = null;
        $this->created_at        = new \DateTime();
        $this->position          = 0;
        $this->taxonomies        = new ArrayCollection();
    }

    /**
     * @return string
     */
    public function __toString()
    {
        return (string) $this->getTitle();
    }

    /**
     * @param $name
     *
     * @return bool
     */
    public function hasAttribute($name)
    {
        foreach ($this->getAttributesGroups() as $group) {
            foreach ($group->getAttributes() as $attribute) {
                if ($attribute->getName() == $name) {
                    return true;
                }
            }
        }

        return false;
    }
    
    /**
     * @return ArrayCollection|UnicatAttributesGroup[]
     */
    public function getAttributesGroups()
    {
        return $this->attributes_groups;
    }

    /**
     * @param ArrayCollection|UnicatAttributesGroup[] $attributes_groups
     *
     * @return $this
     */
    public function setAttributesGroups($attributes_groups)
    {
        $this->attributes_groups = $attributes_groups;

        return $this;
    }

    /**
     * @param UnicatConfiguration $configuration
     *
     * @return $this
     */
    public function setConfiguration(UnicatConfiguration $configuration)
    {
        $this->configuration = $configuration;

        return $this;
    }

    /**
     * @return UnicatConfiguration
     */
    public function getConfiguration()
    {
        return $this->configuration;
    }

    /**
     * @return ArrayCollection|UnicatTaxonomy[]
     */
    public function getTaxonomies()
    {
        return $this->taxonomies;
    }

    /**
     * @param ArrayCollection|UnicatTaxonomy[] $taxonomies
     *
     * @return $this
     */
    public function setTaxonomies($taxonomies)
    {
        $this->taxonomies = $taxonomies;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getToStringPattern()
    {
        return $this->to_string_pattern;
    }

    /**
     * @param null|string $to_string_pattern
     *
     * @return $this
     */
    public function setToStringPattern($to_string_pattern)
    {
        $this->to_string_pattern = $to_string_pattern;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getOrderByAttr()
    {
        return $this->order_by_attr;
    }

    /**
     * @param null|string $order_by_attr
     *
     * @return $this
     */
    public function setOrderByAttr($order_by_attr)
    {
        $this->order_by_attr = $order_by_attr;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getOrderByDirection()
    {
        return $this->order_by_direction;
    }

    /**
     * @param null|string $order_by_direction
     *
     * @return $this
     */
    public function setOrderByDirection($order_by_direction)
    {
        $this->order_by_direction = $order_by_direction;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getContentMinWidth()
    {
        return $this->content_min_width;
    }

    /**
     * @param int|null $content_min_width
     *
     * @return $this
     */
    public function setContentMinWidth($content_min_width)
    {
        $this->content_min_width = $content_min_width;

        return $this;
    }
}

Entity/UnicatTaxonomy.php
<?php

namespace SmartCore\Module\Unicat\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Smart\CoreBundle\Doctrine\ColumnTrait;

/**
 * @ORM\Entity()
 * @ORM\Table(name="unicat__taxonomies",
 *      indexes={
 *          @ORM\Index(columns={"name"}),
 *      }
 * )
 */
class UnicatTaxonomy
{
    use ColumnTrait\Id;
    use ColumnTrait\CreatedAt;
    use ColumnTrait\Name;
    use ColumnTrait\Position;
    use ColumnTrait\TitleNotBlank;
    use ColumnTrait\FosUser;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     */
    protected $title_form;

    /**
     * Множественное вхождение записей в таксономию.
     *
     * @var bool
     *
     * @ORM\Column(type="boolean")
     */
    protected $is_multiple_entries;

    /**
     * Показывать колонку в админке
     *
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default":0})
     */
    protected $is_show_in_admin;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $is_required;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default":0})
     */
    protected $is_default_inheritance;

    /**
     * Древовидная структура.
     *
     * @ORM\Column(type="boolean", options={"default":1})
     */
    protected $is_tree;

    /**
     * @var string
     *
     * @ORM\Column(type="text", nullable=true)
     */
    protected $properties;

    /**
     * @var UnicatConfiguration
     *
     * @ORM\ManyToOne(targetEntity="UnicatConfiguration", inversedBy="taxonomies")
     */
    protected $configuration;

    /**
     * @todo пока не используется.
     *
     * @var UnicatAttribute[]|ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="UnicatAttribute", mappedBy="taxonomies")
     */
    //protected $attributes;

    /**
     * @var UnicatItemType[]
     *
     * @ORM\ManyToMany(targetEntity="UnicatItemType", mappedBy="taxonomies")
     */
    protected $item_types;

    /**
     * UnicatTaxonomy constructor.
     */
    public function __construct()
    {
        $this->attributes = new ArrayCollection();
        $this->created_at = new \DateTime();
        $this->position   = 0;
        $this->properties = null;
        $this->is_default_inheritance = false;
        $this->is_multiple_entries    = false;
        $this->is_required = true;
        $this->is_tree     = true;
        $this->is_show_in_admin = false;
    }

    /**
     * @return string
     */
    public function __toString()
    {
        return (string) $this->getTitle();
    }

    /**
     * @return ArrayCollection|UnicatAttribute[]
     */
    public function getAttributes()
    {
        return $this->attributes;
    }

    /**
     * @param ArrayCollection|UnicatAttribute[] $attributes
     *
     * @return $this
     */
    public function setAttributes($attributes)
    {
        $this->attributes = $attributes;

        return $this;
    }

    /**
     * @return boolean
     */
    public function getIsMultipleEntries()
    {
        return $this->is_multiple_entries;
    }

    /**
     * @return bool
     */
    public function isMultipleEntries()
    {
        return $this->is_multiple_entries;
    }

    /**
     * @param boolean $is_multiple_entries
     *
     * @return $this
     */
    public function setIsMultipleEntries($is_multiple_entries)
    {
        $this->is_multiple_entries = $is_multiple_entries;

        return $this;
    }

    /**
     * @param bool $is_default_inheritance
     *
     * @return $this
     */
    public function setIsDefaultInheritance($is_default_inheritance)
    {
        if (empty($is_default_inheritance)) {
            $is_default_inheritance = 0;
        }

        $this->is_default_inheritance = $is_default_inheritance;

        return $this;
    }

    /**
     * @return bool
     */
    public function getIsDefaultInheritance()
    {
        return $this->is_default_inheritance;
    }

    /**
     * @param bool $is_required
     *
     * @return $this
     */
    public function setIsRequired($is_required)
    {
        if (empty($is_required)) {
            $is_required = 0;
        }

        $this->is_required = $is_required;

        return $this;
    }

    /**
     * @return bool
     */
    public function getIsRequired()
    {
        return $this->is_required;
    }

    /**
     * @return bool
     */
    public function isRequired()
    {
        return $this->is_required;
    }

    /**
     * @return bool
     */
    public function getIsTree()
    {
        return $this->is_tree;
    }

    /**
     * @return bool
     */
    public function isTree()
    {
        return $this->is_tree;
    }

    /**
     * @param bool $is_tree
     *
     * @return $this
     */
    public function setIsTree($is_tree)
    {
        if (empty($is_tree)) {
            $is_tree = 0;
        }

        $this->is_tree = $is_tree;

        return $this;
    }

    /**
     * @return bool
     */
    public function isShowInAdmin(): bool
    {
        return $this->is_show_in_admin;
    }

    /**
     * @param bool $is_show_in_admin
     *
     * @return $this
     */
    public function setIsShowInAdmin($is_show_in_admin)
    {
        $this->is_show_in_admin = $is_show_in_admin;

        return $this;
    }

    /**
     * @param string $properties
     *
     * @return $this
     */
    public function setProperties($properties)
    {
        $this->properties = $properties;

        return $this;
    }

    /**
     * @return string
     */
    public function getProperties()
    {
        return $this->properties;
    }

    /**
     * @param UnicatConfiguration $configuration
     *
     * @return $this
     */
    public function setConfiguration(UnicatConfiguration $configuration)
    {
        $this->configuration = $configuration;

        return $this;
    }

    /**
     * @return UnicatConfiguration
     */
    public function getConfiguration()
    {
        return $this->configuration;
    }

    /**
     * @param string $title_form
     *
     * @return $this
     */
    public function setTitleForm($title_form)
    {
        $this->title_form = $title_form;

        return $this;
    }

    /**
     * @return string
     */
    public function getTitleForm()
    {
        return $this->title_form;
    }
}

Resources/views/Admin/_item_form.html.twig
{{ form_start(form, {'attr':{'class':'form-horizontal well'}}) }}
{{ form_errors(form) }}
<fieldset>
    <div class="tabbable">
        <ul class="nav nav-pills">
            <li class="active"><a href="#base-settings" data-toggle="tab">{{ 'Base settings'|trans }}</a></li>
            <li><a href="#meta-tags" data-toggle="tab">{{ 'Meta tags'|trans }}</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane" id="meta-tags">
                {{ form_widget(form.meta) }}
            </div>
            <div class="tab-pane active" id="base-settings">
                {{ form_widget(form) }}
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                {{ form_rest(form) }}
            </div>
        </div>
    </div>
</fieldset>
{{ form_end(form) }}

{{ elfinder_tinymce_init4('tinymce4', {'width': 980, 'height': 430, 'title': 'Файловый менеджер' }) }}
{{ tinymce_init() }}

Resources/views/Admin/_item_form_content.html.twig
{% include '@UnicatModule/Admin/_item_form.html.twig' %}

Resources/views/Admin/_layout.html.twig
{% extends '@CMS/Admin/module.html.twig' %}

{% if configuration is not defined %}
    {% set configuration = unicat_current_configuration() %}
{% endif %}

{% block title %}&laquo;{{ configuration.title }}&raquo; / Unicat / {{ parent() }}{% endblock %}

{% set page_header = 'Unicat'|trans %}
{% set page_description = 'Module'|trans %}

{% block nav %}

    {% set __selected_inheritance = app.request.attributes.get('__selected_inheritance') %}
    {% set __si = app.request.attributes.set('__selected_inheritance', false) %}

    {% set configurationMenu = knp_menu_get('UnicatModuleBundle:AdminMenu:configuration', [], {
        'configuration': configuration,
    }) %}

    {{ knp_menu_render(configurationMenu, {
        'currentClass': 'active',
        'clear_matcher': false,
    }) }}

    {% set __si = app.request.attributes.set('__selected_inheritance', __selected_inheritance) %}

{% endblock nav %}

Resources/views/Admin/configuration.html.twig
{% extends '@UnicatModule/Admin/_layout.html.twig' %}

{% block title %}{{ parent() }} {% if pagerfanta.haveToPaginate %} [Страница: {{ pagerfanta.currentPage }} из {{ pagerfanta.nbPages }}]{% endif %}{% endblock %}

{% block content %}

    {% if itemType.contentMinWidth is not empty %}
        <style media="all" type="text/css">
            body, html, .wrapper {
                min-width: {{ itemType.contentMinWidth }}px !important;
                overflow-x: auto !important;
            }
        </style>
    {% endif %}

<div class="box box-primary">
    <div class="box-header with-border">

    <a href="{{ path('unicat_admin.item_create', {'configuration': configuration.name, 'type': itemType.id, 'parent_id': app.request.query.get('parent_id')}) }}" class="btn btn-primary pull-right">
        <i class="icon-plus icon-white"></i><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        {{ 'Create record'|trans }}
    </a>

        <ul class="nav nav-pills">
            {% for type in configuration.itemTypes %}
                <li{% if itemType.id == type.id %} class="active"{% endif %}><a href="{{ path('unicat_admin.configuration.items', {'configuration': configuration.name, 'itemTypeId': type.id}) }}">{{ type.title }}</a></li>
            {% endfor %}
        </ul>

        <br>

        {% if parentItem is not empty %}
            <p>Выборка из коллекции: <b>{{ parentItem.type.title }} - {{ parentItem }}</b></p>
        {% endif %}

    <p>Всего: <b>{{ pagerfanta.count }}</b>
        {% if pagerfanta.haveToPaginate %} &nbsp;&nbsp; Страница: {{ pagerfanta.currentPage }} Записей на страницу: {{ pagerfanta.maxPerPage }}{% endif %}
    </p>

    <table class="table table-bordered table-hover">
        <thead><tr>
            <th style="width: 1%;">id</th>
            <th>{{ 'Slug'|trans }}</th>
            {% for attribute in configuration.attributes %}
                {% if attribute.showInAdmin and itemType.hasAttribute(attribute.name) %}<th>{{ attribute.title }}</th>{% endif %}
            {% endfor %}
            {% for taxonomy in itemType.taxonomies if taxonomy.isShowInAdmin == true %}
                <th>{{ taxonomy }}</th>
            {% endfor %}
            <th>{{ 'Created at'|trans }}</th>
            <th>Действия</th>
        </tr></thead>
        <tbody>
        {% for item in pagerfanta %}
            <tr>
                <td>{{ item.id }}</td>
                <td><a href="{{ path('unicat_admin.item_edit', {'configuration': configuration.name, 'id': item.id}) }}"{% if item.isDisabled %} style="text-decoration: line-through;"{% endif %}>{{ item.slug }}</a>
                </td>
                {% for attribute in configuration.attributes %}
                    {% if attribute.showInAdmin and itemType.hasAttribute(attribute.name) %}
                        <td>
                            {% set attr_item = item.attribute(attribute.name) %}

                            {% if attr_item is iterable and attribute.type == 'unicat_item' %}
                                <ul>
                                    {% for attr_item_2 in attr_item %}
                                        <li>
                                            <a href="{{ path('unicat_admin.configuration.items', {
                                                'configuration': configuration.name,
                                                'itemTypeId': item.type.id,
                                                'parent_id': attr_item_2.id
                                            }) }}"{% if item.isDisabled %} style="text-decoration: line-through;"{% endif %} title="Выборка записей '{{ item.type.title }}' из коллекции: {{ attribute.title }}">
                                                {{ attr_item_2 }}
                                            </a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            {% else %}
                                {% if attribute.type == 'unicat_item' and attr_item is not empty %}
                                    <a href="{{ path('unicat_admin.configuration.items', {
                                        'configuration': configuration.name,
                                        'itemTypeId': item.type.id,
                                        'parent_id': attr_item.id
                                    }) }}"{% if item.isDisabled %} style="text-decoration: line-through;"{% endif %} title="Выборка записей '{{ item.type.title }}' из коллекции: {{ attribute.title }}">
                                {% else %}
                                    <a href="{{ path('unicat_admin.item_edit', {'configuration': configuration.name, 'id': item.id}) }}"{% if item.isDisabled %} style="text-decoration: line-through;"{% endif %}>
                                {% endif %}

                                {% if attribute.type == 'image' %}
                                    {{ smart_media_img(attr_item, '100x100') }}
                                {% elseif attribute.type == 'gallery' %}
                                    {% if attr_item['galleryName'] is not empty %}
                                        <b>{{ attr_item['galleryName'] }}</b><br>
                                    {% endif %}

                                    {% set gallery_images_count = 0 %}
                                    {% for img in attr_item['images'] %}
                                        {% if gallery_images_count == 0 %}
                                            {{ smart_media_img(img.id, '100x100', img.title) }}
                                        {% endif %}

                                        {% set gallery_images_count = gallery_images_count + 1 %}
                                    {% endfor %}

                                    {% if gallery_images_count > 1 %}
                                        <p>и ещё {{ gallery_images_count }}...</p>
                                    {% endif %}
                                {% elseif attribute.type == 'choice' %}
                                    {{ attribute.valueByChoice(attr_item) }}
                                {% elseif attribute.type == 'date' or attribute.type == 'datetime'%}
                                    {{ attr_item|localizeddate }}
                                {% else %}
                                    {{ attr_item }}
                                {% endif %}
                                </a>

                            {% endif %}
                        </td>
                    {% endif %}
                {% endfor %}
                {% for taxonomy in itemType.taxonomies if taxonomy.isShowInAdmin == true %}
                    <td>
                        {% for taxon in item.taxons if taxon.taxonomy.id == taxonomy.id %}
                            {{ taxon }},
                        {% endfor %}
                    </td>
                {% endfor %}
                <td>{{ item.createdAt|localizeddate() }}</td>
                <td>
                    {% for item_type_child in itemsTypesChildren %}
                        <a href="{{ path('unicat_admin.item_create', {
                            'configuration': item.type.configuration.name,
                            'type': item_type_child.id,
                            'parent_id': item.id,
                        }) }}" class="btn btn-success btn-xs link-create-item_{{ item_type_child.name }}-type_{{ item.type.name }}">
                            <i class="icon-plus icon-white"></i><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                            Создать запись &laquo;{{ item_type_child.title }}&raquo;
                        </a>
                        <br class="link-create-item_{{ item_type_child.name }}-type_{{ item.type.name }}-br">
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if pagerfanta.haveToPaginate %}
        Страница: {{ pagerfanta.currentPage }} Записей на страницу: {{ pagerfanta.maxPerPage }}
        {{ pagerfanta(pagerfanta, 'twitter_bootstrap_translated', {'css_container_class': 'pagination pagination-centered', 'proximity': 5}) }}
    {% endif %}

    </div>
</div>

{% endblock content %}

Resources/views/Admin/configuration_settings.html.twig
{% extends '@UnicatModule/Admin/_layout.html.twig' %}

{% block title %}{{ 'Settings'|trans }} / {{ parent() }}{% endblock %}

{% block content %}

<div class="box box-primary">
    <div class="box-header with-border">

        {% include '@UnicatModule/help/settings.html.twig' %}

        <h2>{{ 'Configuration settings'|trans }}: {{ configuration.name }}</h2>

        {% if configuration.mediaCollection is not empty %}
            <p><b>Медиаколлекция</b>: <a href="{{ path('cms_admin_config_media_edit_collection', {'id': configuration.mediaCollection.id}) }}">{{ configuration.mediaCollection }}</a></p>
        {% endif %}

        {{ form(form, {'attr':{'class':'form-horizontal well'}}) }}

    </div>
</div>

{% endblock content %}

Resources/views/Admin/item_create.html.twig
{% extends '@UnicatModule/Admin/_layout.html.twig' %}

{% block title %} {{ 'Create record'|trans }} / &laquo;{{ configuration.title }}&raquo; / {{ parent() }}{% endblock %}

{% block content %}

<div class="box box-primary">
    <div class="box-header with-border">

    <h2>{{ 'Create record'|trans }}: &laquo;{{ itemType.title }}&raquo;</h2>

        {% include '@UnicatModule/Admin/_item_form_content.html.twig' %}

    </div>
</div>

{% endblock content %}

Resources/views/Admin/items_type_create.html.twig
{% extends '@UnicatModule/Admin/configuration.html.twig' %}

{% block title %}{{ 'Item types create'|trans }} / {{ parent() }}{% endblock %}

{% block content %}

<div class="box box-primary">
    <div class="box-header with-border">

    <h3>{{ 'Item types create'|trans }}</h3>

    {{ form(form, {'attr': {'class': 'form-horizontal well'}}) }}

    </div>
</div>

{% endblock content %}

Resources/views/Admin/items_types.html.twig
{% extends '@UnicatModule/Admin/_layout.html.twig' %}

{% block title %} {{ 'Items types'|trans }} / {{ parent() }}{% endblock %}

{% block content %}

<div class="box box-primary">
    <div class="box-header with-border">

        <a href="{{ path('unicat_admin.items_type_create', {'configuration': configuration.name}) }}" class="btn btn-success pull-right">
            <i class="icon-plus icon-white"></i><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> {{ 'Create'|trans }}
        </a>

        <h2>{{ 'Items types'|trans }}</h2>

        <table class="table table-bordered table-hover">
            <thead><tr>
                <th style="width: 1%;">id</th>
                <th>{{ 'Title'|trans }}</th>
                <th>{{ 'Name'|trans }}</th>
                <th>{{ 'Position'|trans }}</th>
                <th>{{ 'Attributes groups'|trans }}</th>
                <th>{{ 'Taxonomies'|trans }}</th>
                {#<th>{{ 'Created at'|trans }}</th>#}
            </tr></thead>
            <tbody>
            {% for type in types %}
                <tr>
                    <td>{{ type.id }}</td>
                    <td><a href="{{ path('unicat_admin.items_type_edit', {'configuration': configuration.name, 'id': type.id}) }}">{{ type.title }}</a></td>
                    <td><a href="{{ path('unicat_admin.items_type_edit', {'configuration': configuration.name, 'id': type.id}) }}">{{ type.name }}</a></td>
                    <td><a href="{{ path('unicat_admin.items_type_edit', {'configuration': configuration.name, 'id': type.id}) }}">{{ type.position }}</a></td>
                    <td>
                        {% for group in type.attributesGroups %}
                            {{ group }},
                        {% endfor %}
                    </td>
                    <td>
                        {% for taxonomy in type.taxonomies %}
                            {{ taxonomy }},
                        {% endfor %}
                    </td>
                    {#<td>{{ type.createdAt|localizeddate() }}</td>#}
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
</div>

{% endblock content %}