Entity/UnicatAttribute.php
<?php

namespace SmartCore\Module\Unicat\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Smart\CoreBundle\Doctrine\ColumnTrait;
use SmartCore\Bundle\CMSBundle\Container;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Yaml\Yaml;

/**
 * @ORM\Entity(repositoryClass="SmartCore\Module\Unicat\Entity\UnicatAttributeRepository")
 * @ORM\Table(name="unicat__attributes",
 *      indexes={
 *          @ORM\Index(columns={"is_enabled"}),
 *          @ORM\Index(columns={"show_in_admin"}),
 *          @ORM\Index(columns={"show_in_list"}),
 *          @ORM\Index(columns={"show_in_view"}),
 *          @ORM\Index(columns={"position"}),
 *      },
 *      uniqueConstraints={
 *          @ORM\UniqueConstraint(columns={"name", "configuration_id"}),
 *      },
 * )
 *
 * @UniqueEntity(fields={"name", "configuration"}, message="Имя атрибута должно быть уникальным.")
 */
class UnicatAttribute
{
    use ColumnTrait\Id;
    use ColumnTrait\IsEnabled;
    use ColumnTrait\CreatedAt;
    use ColumnTrait\Description;
    use ColumnTrait\Position;
    use ColumnTrait\TitleNotBlank;
    use ColumnTrait\FosUser;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     * @Assert\NotBlank()
     * @Assert\Regex(
     *      pattern="/^[a-z][a-z0-9_]+$/",
     *      htmlPattern="^[a-z][a-z0-9_]+$",
     *      message="Имя может состоять только из латинских букв в нижнем регистре, символов подчеркивания и цифр, но первый символ должен быть буква."
     * )
     *
     * @todo перевод сообщения
     */
    protected $name;

    /**
     * @ORM\Column(type="string", length=32)
     */
    protected $type;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true, options={"default":"<p>"})
     */
    protected $open_tag;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true, options={"default":"</p>"})
     */
    protected $close_tag;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default":0})
     */
    protected $is_dedicated_table;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default":0})
     */
    protected $is_link;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default":0})
     */
    protected $is_required;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default":1})
     */
    protected $is_show_title;

    /**
     * Отсновной атрибут? Используется для фильтрации "основные" и "все" свойства.
     *
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default":1})
     */
    protected $is_primary;

    /**
     * Отображать в списке администратора.
     *
     * @var bool
     *
     * @ORM\Column(type="boolean")
     */
    protected $show_in_admin;

    /**
     * Отображать в списке записей.
     *
     * @var bool
     *
     * @ORM\Column(type="boolean")
     */
    protected $show_in_list;

    /**
     * Отображать при просмотре записи.
     *
     * @var bool
     *
     * @ORM\Column(type="boolean")
     */
    protected $show_in_view;

    /**
     * @var array
     *
     * @ORM\Column(type="array")
     */
    protected $params;

    /**
     * @var array
     *
     * @ORM\Column(type="text", nullable=true)
     */
    protected $params_yaml;

    /**
     * Связывать items_type (если указан) как "много ко многим".
     *
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default":0})
     */
    protected $is_items_type_many2many;

    /**
     * @var UnicatConfiguration
     *
     * @ORM\ManyToOne(targetEntity="UnicatConfiguration", inversedBy="attributes")
     */
    protected $configuration;

    /**
     * Атрибут - колекция других типов записей.
     *
     * @var UnicatItemType|null
     *
     * @ORM\ManyToOne(targetEntity="UnicatItemType")
     */
    protected $items_type;

    /**
     * @var UnicatAttributesGroup[]|ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="UnicatAttributesGroup", inversedBy="attributes", cascade={"persist"}, fetch="EXTRA_LAZY")
     * @ORM\JoinTable(name="unicat__attributes_groups_relations",
     *      joinColumns={@ORM\JoinColumn(name="attribute_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="group_id", referencedColumnName="id")}
     * )
     */
    protected $groups;

    /**
     * @var string
     */
    protected $update_all_records_with_default_value;

    /**
     * UnicatAttribute constructor.
     */
    public function __construct()
    {
        $this->created_at       = new \DateTime();
        $this->groups           = new ArrayCollection();
        $this->is_dedicated_table = false;
        $this->is_enabled       = true;
        $this->is_link          = false;
        $this->is_required      = false;
        $this->is_show_title    = true;
        $this->is_primary       = true;
        $this->is_items_type_many2many = false;
        $this->show_in_view     = true;
        $this->params           = [];
        $this->params_yaml      = null;
        $this->position         = 0;
        $this->open_tag         = '<p>';
        $this->close_tag        = '</p>';
    }

    /**
     * @see getName
     *
     * @return string
     */
    public function __toString()
    {
        return (string) $this->getName();
    }

    /**
     * @return null|string
     */
    public function getValueClassName()
    {
        if ($this->is_dedicated_table) {
            $className = 'Value';

            foreach (explode('_', $this->name) as $namePart) {
                $className .= ucfirst($namePart);
            }

            return $className;
        }

        return null;
    }

    /**
     * Получить значение из списка.
     *
     * @param int|string $id
     *
     * @return int|null|string
     */
    public function getValueByChoice($id)
    {
        if (isset($this->params['form']['choices'])) {
            foreach ($this->params['form']['choices'] as $name => $value) {
                if ($value == $id) {
                    return $name;
                }
            }
        }

        return null;
    }

    /**
     * Получение имени в формате CamelCase
     *
     * @return string
     */
    public function getNameCamelCase()
    {
        $str = '';
        foreach (explode('_', $this->getName()) as $val) {
            if (!empty($val)) {
                $str .= ucfirst($val);
            }
        }

        return $str;
    }

    /**
     * Получение вариантов выбора для типа choice
     *
     * @return array|bool
     */
    public function getChoices()
    {
        $choices = [];
        if (isset($this->params['form']['choices'])) {
            $choices = array_flip($this->params['form']['choices']);
        }

        return $choices;
    }

    /**
     * @return string
     */
    public function getValueClassNameWithNameSpace()
    {
        return $this->getConfiguration()->getEntitiesNamespace().$this->getValueClassName();
    }

    /**
     * @param bool $is_dedicated_table
     *
     * @return $this
     */
    public function setIsDedicatedTable($is_dedicated_table)
    {
        $this->is_dedicated_table = $is_dedicated_table;

        return $this;
    }

    /**
     * @return bool
     */
    public function isDedicatedTable()
    {
        return $this->is_dedicated_table;
    }

    /**
     * @return bool
     */
    public function getIsDedicatedTable()
    {
        return $this->is_dedicated_table;
    }

    /**
     * @return bool
     */
    public function isIsLink()
    {
        return $this->is_link;
    }

    /**
     * @param bool $is_link
     *
     * @return $this
     */
    public function setIsLink($is_link)
    {
        $this->is_link = $is_link;

        return $this;
    }

    /**
     * @param bool $is_required
     *
     * @return $this
     */
    public function setIsRequired($is_required)
    {
        $this->is_required = $is_required;

        return $this;
    }

    /**
     * @return bool
     */
    public function getIsRequired()
    {
        return $this->is_required;
    }

    /**
     * @return bool
     */
    public function isIsShowTitle()
    {
        return $this->is_show_title;
    }

    /**
     * @param bool $is_show_title
     *
     * @return $this
     */
    public function setIsShowTitle($is_show_title)
    {
        $this->is_show_title = $is_show_title;

        return $this;
    }

    /**
     * @return bool
     */
    public function isIsPrimary(): bool
    {
        return $this->is_primary;
    }

    /**
     * @param bool $is_primary
     *
     * @return $this
     */
    public function setIsPrimary($is_primary)
    {
        $this->is_primary = $is_primary;

        return $this;
    }

    /**
     * @return bool
     */
    public function getIsItemsTypeMany2many(): bool
    {
        return $this->is_items_type_many2many;
    }

    /**
     * @return bool
     */
    public function isItemsTypeMany2many(): bool
    {
        return $this->is_items_type_many2many;
    }

    /**
     * @param bool $is_items_type_many2many
     *
     * @return $this
     */
    public function setIsItemsTypeMany2many($is_items_type_many2many)
    {
        $this->is_items_type_many2many = $is_items_type_many2many;

        return $this;
    }

    /**
     * @return UnicatAttributesGroup[]|ArrayCollection
     */
    public function getGroups()
    {
        return $this->groups;
    }

    /**
     * @param UnicatAttributesGroup[] $groups
     *
     * @return $this
     */
    public function setGroups($groups)
    {
        $this->groups = $groups;

        return $this;
    }

    /**
     * @param array $params
     *
     * @return $this
     */
    public function setParams(array $params = [])
    {
        $this->params = $params;

Controller/AdminStructureController.php
<?php

namespace SmartCore\Module\Unicat\Controller;

use Smart\CoreBundle\Controller\Controller;
use SmartCore\Module\Unicat\Entity\UnicatConfiguration;
use Symfony\Component\HttpFoundation\Request;

class AdminStructureController extends Controller
{
    /**
     * @param Request $request
     * @param int     $structure_id
     * @param int     $id
     * @param string  $configuration
     *
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function taxonEditAction(Request $request, $structure_id, $id, $configuration)
    {
        $unicat = $this->get('unicat'); // @todo перевести всё на $ucm.
        $ucm    = $unicat->getConfigurationManager($configuration);

        $structure = $ucm->getStructure($structure_id);
        $taxon     = $ucm->getTaxon($id);

        $form = $ucm->getTaxonEditForm($taxon);

        if ($request->isMethod('POST')) {
            $form->handleRequest($request);

            if ($form->get('cancel')->isClicked()) {
                return $this->redirectToStructureAdmin($ucm->getConfiguration(), $structure_id);
            }

            if ($form->get('update')->isClicked() and $form->isValid()) {
                $unicat->updateTaxon($form->getData());
                $this->get('session')->getFlashBag()->add('success', 'Категория обновлена');

                return $this->redirectToStructureAdmin($ucm->getConfiguration(), $structure_id);
            }

            if ($form->has('delete') and $form->get('delete')->isClicked()) {
                $unicat->deleteTaxon($form->getData());
                $this->get('session')->getFlashBag()->add('success', 'Категория удалена');

                return $this->redirectToStructureAdmin($ucm->getConfiguration(), $structure_id);
            }
        }

        return $this->render('UnicatModule:AdminStructure:taxon_edit.html.twig', [
            'configuration' => $structure->getConfiguration(), // @todo убрать, это пока для наследуемого шаблона.
            'taxon'         => $taxon,
            'form'          => $form->createView(),
            'structure'     => $structure,
        ]);
    }

    /**
     * @param string $configuration
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexAction($configuration)
    {
        $configuration = $this->get('unicat')->getConfiguration($configuration);

        if (empty($configuration)) {
            return $this->render('@CMS/Admin/not_found.html.twig');
        }

        return $this->render('UnicatModule:AdminStructure:index.html.twig', [
            'configuration'     => $configuration,
        ]);
    }

    /**
     * @param Request $request
     * @param int $id
     * @param string|int $configuration
     * @param int|null $parent_id
     *
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function structureAction(Request $request, $id, $configuration, $parent_id = null)
    {
        $unicat     = $this->get('unicat'); // @todo перевести всё на $ucm.
        $ucm        = $unicat->getConfigurationManager($configuration);
        $structure  = $unicat->getStructure($id);

        $parentTaxon = $parent_id ? $ucm->getTaxonRepository()->find($parent_id) : null;

        $form = $ucm->getTaxonCreateForm($structure, [], $parentTaxon);

        if ($request->isMethod('POST')) {
            $form->handleRequest($request);
            if ($form->isValid()) {
                $unicat->createTaxon($form->getData());
                $this->get('session')->getFlashBag()->add('success', 'Категория создана');

                return $this->redirectToStructureAdmin($ucm->getConfiguration(), $id);
            }
        }

        return $this->render('UnicatModule:AdminStructure:structure.html.twig', [
            'configuration' => $structure->getConfiguration(), // @todo убрать, это пока для наследуемого шаблона.
            'form'          => $form->createView(),
            'structure'     => $structure,
        ]);
    }

    /**
     * @param Request $request
     * @param string $configuration
     *
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function createAction(Request $request, $configuration)
    {
        $ucm  = $this->get('unicat')->getConfigurationManager($configuration);
        $form = $ucm->getStructureCreateForm();

        if ($request->isMethod('POST')) {
            $form->handleRequest($request);

            if ($form->get('cancel')->isClicked()) {
                return $this->redirect($this->generateUrl('unicat_admin.structures_index', ['configuration' => $configuration]));
            }

            if ($form->get('create')->isClicked() and $form->isValid()) {
                $ucm->updateStructure($form->getData());
                $this->get('session')->getFlashBag()->add('success', 'Структура создана');

                return $this->redirect($this->generateUrl('unicat_admin.structures_index', ['configuration' => $configuration]));
            }
        }

        return $this->render('UnicatModule:AdminStructure:create.html.twig', [
            'form'          => $form->createView(),
            'configuration' => $ucm->getConfiguration(), // @todo убрать, это пока для наследуемого шаблона.
        ]);
    }

    /**
     * @param Request $request
     * @param int $id
     * @param string|int $configuration
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function editAction(Request $request, $id, $configuration)
    {
        $ucm = $this->get('unicat')->getConfigurationManager($configuration);
        $form = $ucm->getStructureEditForm($ucm->getStructure($id));

        if ($request->isMethod('POST')) {
            $form->handleRequest($request);

            if ($form->get('cancel')->isClicked()) {
                return $this->redirect($this->generateUrl('unicat_admin.structures_index', ['configuration' => $configuration]));
            }

            if ($form->get('update')->isClicked() and $form->isValid()) {
                $ucm->updateStructure($form->getData());
                $this->get('session')->getFlashBag()->add('success', 'Структура обновлена');

                return $this->redirect($this->generateUrl('unicat_admin.structures_index', ['configuration' => $configuration]));
            }
        }

        return $this->render('UnicatModule:AdminStructure:edit.html.twig', [
            'form'          => $form->createView(),
            'configuration' => $ucm->getConfiguration(), // @todo убрать, это пока для наследуемого шаблона.
        ]);
    }

    /**
     * @param UnicatConfiguration $configuration
     * @param int $structure_id
     *
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    protected function redirectToStructureAdmin(UnicatConfiguration $configuration, $structure_id)
    {
        $request = $this->get('request_stack')->getCurrentRequest();

        $url = $request->query->has('redirect_to')
            ? $request->query->get('redirect_to')
            : $this->generateUrl('unicat_admin.structure', ['id' => $structure_id, 'configuration' => $configuration->getName()]);

        return $this->redirect($url);
    }
}

Resources/views/AdminStructure/category_edit.html.twig
{% extends '@UnicatModule/Admin/_layout.html.twig' %}

{% block title %}{{ 'Edit category'|trans }} &laquo;{{ category.title }}&raquo; / {{ parent() }}{% endblock %}

{% block content %}

<div class="box box-primary">
    <div class="box-header with-border">

    <h3>{{ 'Edit category'|trans }} &laquo;{{ category.title }}&raquo;</h3>

        <a href="../"><i class="fa fa-arrow-circle-o-left"></i> Назад к просмотру всех категорий</a>

    {{ form_start(form, {'attr':{'class': 'form-horizontal well'}}) }}
    {{ form_errors(form) }}
    <fieldset>
        <div class="tabbable">
            <ul class="nav nav-pills">
                <li class="active"><a href="#base-settings" data-toggle="tab">{{ 'Base settings'|trans }}</a></li>
                {% if form.properties %}<li><a href="#cat-properties" data-toggle="tab">{{ 'Properties'|trans }}</a></li>{% endif %}
                <li><a href="#meta-tags" data-toggle="tab">{{ 'Meta tags'|trans }}</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane" id="meta-tags">
                    {{ form_widget(form.meta) }}
                </div>
                {% if form.properties %}
                <div class="tab-pane" id="cat-properties">
                    {{ form_widget(form.properties) }}
                </div>
                {% endif %}
                <div class="tab-pane active" id="base-settings">
                    {{ form_widget(form) }}
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    {{ form_rest(form) }}
                </div>
            </div>
        </div>
    </fieldset>
    {{ form_end(form) }}

    {#{{ tinymce_init3() }}#}
    {#{{ elfinder_tinymce_init() }}#}

    {{ elfinder_tinymce_init4('tinymce4', {'width': 980, 'height': 430, 'title': 'Файловый менеджер' }) }}
    {{ tinymce_init() }}

    </div>
</div>

{% endblock content %}

Resources/views/AdminStructure/create.html.twig
{% extends '@UnicatModule/Admin/configuration.html.twig' %}

{% block title %}{{ 'Structure create'|trans }} / {{ parent() }}{% endblock %}

{% block content %}

<div class="box box-primary">
    <div class="box-header with-border">

    <h3>{{ 'Structure create'|trans }}</h3>

    {{ form(form, {'attr': {'class': 'form-horizontal well'}}) }}

    </div>
</div>

{% endblock content %}

Resources/views/AdminStructure/index.html.twig
{% extends '@UnicatModule/Admin/_layout.html.twig' %}

{% block title %}{{ 'Taxonomy'|trans }} / {{ parent() }}{% endblock %}

{% block content %}

<div class="box box-primary">
    <div class="box-header with-border">

    <a href="{{ path('unicat_admin.structure_create', {'configuration': configuration.name}) }}" class="btn btn-success pull-right">
        <i class="icon-plus icon-white"></i><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> {{ 'Create'|trans }}
    </a>

    <h3>{{ 'Taxonomy'|trans }}</h3>

    <table class="table table-bordered table-hover">
        <thead><tr>
            <th style="width: 1%;">id</th>
            <th>{{ 'Title'|trans }}</th>
            <th>{{ 'Name'|trans }}</th>
            <th>{{ 'Is multiple entries'|trans }}</th>
            <th>{{ 'Is required'|trans }}</th>
            <th>{{ 'Is tree'|trans }}</th>
            <th>{{ 'Created at'|trans }}</th>
        </tr></thead>
        <tbody>
        {% for item in configuration.structures %}
            <tr>
                <td>{{ item.id }}</td>
                <td>
                    <a href="{{ path('unicat_admin.structure', {'id': item.id, 'configuration': item.configuration.name}) }}">{{ item.title }}</a>
                    <a href="{{ path('unicat_admin.structure_edit', {'id': item.id, 'configuration': item.configuration.name}) }}" style="float: right;" title="Редактирование структуры">
                        <i class="icon-edit" title="Edit"></i><span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                    </a>
                </td>
                <td>{{ item.name }}</td>
                <td>{{ item.isMultipleEntries }}</td>
                <td>{{ item.isRequired }}</td>
                <td>{{ item.isTree }}</td>
                <td>{{ item.createdAt|date() }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    </div>
</div>

{% endblock content %}

Resources/views/AdminStructure/structure.html.twig
{% extends '@UnicatModule/Admin/configuration.html.twig' %}

{% block title %}{{ 'Structure'|trans }} &laquo;{{ structure.title }}&raquo; / {{ parent() }}{% endblock %}

{% block content %}

<div class="box box-primary">
    <div class="box-header with-border">

        <div class="row">

        <div class="col-md-12">
            <h3>{{ 'Structure'|trans }} &laquo;{{ structure.title }}&raquo;</h3>
        </div>

        <div class="span3 col-md-4">
            {{ form(form, {'attr': {'class': 'form-horizontal well'} }) }}
        </div>

        <div class="span8 col-md-8">
            {% set menuItem = knp_menu_get('UnicatModule:TaxonMenu:adminTree', [], {
                'taxonClass': structure.configuration.taxonClass,
                'structure': structure
            }) %}
            {{ knp_menu_render(menuItem, {
                'currentClass': 'active',
                'clear_matcher': false,
            }) }}
        </div>

        </div>
    </div>
</div>

{% endblock content %}